INSERT INTO airbnbdata.logement (user_id_id,prix,taille,description,couchage,is_active,adresse,code_postal,ville,pays,image_path,name) VALUES
	 (10,348,42.0,'id doloremque deleniti libero adipisci saepe quidem autem velit consequatur sint dignissimos delectus est et dolorem qui ratione non dolores consequatur voluptates omnis commodi quibusdam perspiciatis id dicta est accusantium',5,1,'voluptas repellendus cupiditate in eius ipsa tempora quasi at et',4357,'odit et quod','Porto Rico','telechargement.jpg','qui autem reprehenderit'),
	 (10,136,91.0,'consequatur aut aut ea earum eius dignissimos dolorem qui delectus magni eum non pariatur libero aut fuga possimus autem eum vel dolore quas repudiandae voluptatem magni nesciunt quam eius deserunt',4,1,'deleniti et molestiae eum quasi deleniti velit maiores voluptas sint',7392,'itaque esse dolores','Honduras','telechargement.jpg','facilis quam dolor'),
	 (10,362,59.0,'nihil sapiente quibusdam magnam eum est vel id nihil in corporis dolor sed nesciunt ipsam similique nam veniam fugit quibusdam voluptatem voluptatem necessitatibus error aut aut qui animi nihil nulla',5,1,'quibusdam ut et quis aut natus deserunt possimus itaque voluptatibus',9515,'quos similique hic','Lithuanie','telechargement.jpg','sed eaque magnam'),
	 (10,304,92.0,'voluptas laudantium voluptatem qui deleniti atque ducimus cum quisquam voluptatem nihil voluptates aliquam ut est voluptatum ut perspiciatis aut voluptas delectus consequatur voluptatem eos ipsum voluptatibus enim repellendus optio officia',3,1,'voluptatem autem facere id non dicta et est et itaque',4202,'et voluptatem sit','São Tomé et Príncipe (Rép.)','telechargement.jpg','tempore inventore nemo'),
	 (10,351,65.0,'recusandae ut possimus tempora vel aut doloremque tempora beatae explicabo facilis magnam aut voluptatum cupiditate repudiandae minima aut hic enim laboriosam recusandae iure voluptatem repellendus dolorum corporis dolor sit sunt',4,1,'sit in suscipit provident est provident eligendi dolore vero et',1299,'qui voluptatem laborum','Samoa','telechargement.jpg','explicabo omnis qui'),
	 (10,323,78.0,'quas incidunt alias cum fugit odio saepe pariatur veritatis dolorem ut aliquam eaque sunt aut vero dignissimos explicabo voluptatem praesentium sit dolorem quod consequatur et sit recusandae voluptatem tempore ad',3,1,'qui nemo perferendis vitae beatae vero et cupiditate facilis aliquid',9349,'molestiae non asperiores','Samoa','telechargement.jpg','modi est qui'),
	 (10,170,38.0,'deleniti a assumenda et est consequatur autem impedit earum voluptatem minima hic commodi cumque possimus quis mollitia fuga et eveniet cupiditate repellendus qui et enim velit perferendis soluta similique quia',3,1,'ut quia magnam laudantium corporis incidunt dolore veniam nostrum reprehenderit',5719,'fugit id expedita','Mongolie','telechargement.jpg','non non tempore'),
	 (10,139,37.0,'velit optio quia omnis velit ut corrupti est blanditiis nobis alias voluptatum minima officia est aut exercitationem accusantium molestiae rem doloribus dolore deserunt similique sapiente sed sequi consequuntur et qui',3,1,'occaecati exercitationem architecto dolores eum qui non eveniet et explicabo',7887,'eveniet maxime ea','Porto Rico','telechargement.jpg','impedit ut qui'),
	 (10,214,62.0,'repudiandae qui aperiam fuga iure soluta eum dicta placeat ratione officiis iste mollitia optio eveniet dicta suscipit aliquam quam repellat et ipsa adipisci nobis ipsam quia sapiente nam quibusdam quia',2,1,'quis aut odit est alias maxime omnis quisquam et optio',6669,'quas voluptas eum','Namibie','telechargement.jpg','et unde perferendis'),
	 (10,390,81.0,'dolor neque odit doloribus architecto recusandae quaerat aspernatur sed quo expedita et et voluptates consequatur modi temporibus id voluptatem beatae reiciendis assumenda architecto magni assumenda natus quia voluptate fuga distinctio',4,1,'aut veniam accusamus id ut doloremque modi dolore sunt qui',1184,'velit vero vel','Turkménistan','telechargement.jpg','iste illum voluptatem');
INSERT INTO airbnbdata.logement (user_id_id,prix,taille,description,couchage,is_active,adresse,code_postal,ville,pays,image_path,name) VALUES
	 (10,183,43.0,'minus non eveniet tempore quasi eum ad soluta quia maxime ducimus ipsum impedit quia dolorum hic qui et illo aliquam et necessitatibus est quibusdam impedit ullam asperiores sed similique cum',3,1,'nihil dolores rerum dolorum voluptatem in sequi quos atque quibusdam',9905,'perferendis voluptatum rerum','Nepal','telechargement.jpg','est nemo nisi'),
	 (10,386,36.0,'dolorem repellendus sunt maxime consequatur fuga temporibus dicta et nisi expedita dicta mollitia aut nihil corrupti commodi laudantium harum quam itaque fuga similique consequatur et voluptates itaque asperiores quo ut',3,1,'rem repudiandae voluptas ipsa aperiam aut perspiciatis temporibus aut voluptatibus',1085,'et molestiae sunt','Paraguay','telechargement.jpg','aut quaerat quos'),
	 (10,470,46.0,'aut voluptatem voluptas earum nam quis veniam illum expedita ea aperiam non labore ea totam expedita magnam quis fugit dolor in consequatur deleniti totam fugit repellendus voluptatibus quo a sed',2,1,'nulla tempore qui quos corrupti nemo dicta doloribus et impedit',4149,'vel odio aliquam','Cocos (Îles)','telechargement.jpg','aut sunt iusto'),
	 (10,279,55.0,'qui tempore sint ex rem pariatur quis tempora ab eveniet quia dolorem consequatur ipsum aperiam ab et id quos aspernatur officia sed voluptatibus ut maiores soluta harum aut veniam ut',4,1,'possimus voluptas ad eligendi accusamus in velit dolores enim cumque',7654,'perspiciatis deleniti quasi','Macédoine','telechargement.jpg','nihil exercitationem id'),
	 (10,440,58.0,'non fugit non consequatur harum veniam ipsa enim quia odio debitis illo animi voluptatum eligendi quo aut rem pariatur perspiciatis distinctio explicabo officiis magni optio explicabo veniam est ut consectetur',2,1,'doloribus provident voluptatibus eaque sit cupiditate aliquam fugit sint consequuntur',6026,'natus voluptas quia','Madagascar','telechargement.jpg','est voluptatem qui'),
	 (10,449,92.0,'repudiandae et consequatur odio eveniet aut eveniet qui at incidunt cupiditate cupiditate est repudiandae excepturi voluptatem corrupti voluptate in sit et hic ut error ullam voluptatibus voluptas enim et praesentium',4,1,'veniam aliquid porro deleniti quos rerum qui placeat eos quo',3435,'accusamus et voluptas','Tanzanie','telechargement.jpg','ut ut tenetur'),
	 (10,471,53.0,'veritatis asperiores sapiente ea dolor eos excepturi odit veritatis accusantium cupiditate soluta et quaerat adipisci iusto maxime nobis eos corrupti doloremque reprehenderit consequuntur ut eum ipsam sunt rerum doloremque inventore',2,1,'illum atque consequatur impedit perferendis voluptates assumenda perspiciatis consectetur rerum',3132,'illo dolorem harum','Tokelau','telechargement.jpg','dolor repudiandae ex'),
	 (10,494,99.0,'maiores est quas consectetur laborum illum vel consectetur et consequuntur inventore aut quis amet illo dicta et assumenda cumque vel alias possimus repudiandae error debitis eveniet atque labore perspiciatis autem',1,1,'aut asperiores harum ad et necessitatibus suscipit et quia ullam',5642,'esse voluptatum vero','Thailande','telechargement.jpg','aut accusantium quasi'),
	 (10,258,89.0,'quisquam et quis earum laboriosam quos in quasi hic rerum repellat repellendus est natus beatae voluptas asperiores sit quam illo et repudiandae quia et officiis perspiciatis et delectus odit ducimus',4,1,'expedita minima ut aspernatur rerum omnis facilis doloribus aut vero',1712,'magnam sint accusantium','Algérie','telechargement.jpg','voluptate et illo'),
	 (10,146,34.0,'et sunt rem dolores possimus alias velit reiciendis alias quos alias perspiciatis eos id rerum sit quam maxime eligendi in labore id eaque provident consequatur facere et voluptatem explicabo aspernatur',3,1,'iusto ut qui est enim vel odit beatae dolor officia',4757,'rem qui laborum','Trinité et Tobago','telechargement.jpg','earum porro vero');
INSERT INTO airbnbdata.logement (user_id_id,prix,taille,description,couchage,is_active,adresse,code_postal,ville,pays,image_path,name) VALUES
	 (10,165,32.0,'aut tempore molestias inventore asperiores optio aut quae eum nemo necessitatibus optio est sed et perspiciatis corrupti excepturi impedit rerum dicta qui voluptas asperiores veniam eaque aut qui maxime quia',3,1,'vero deserunt sed eius culpa officiis libero ipsam a ut',4574,'ratione ab voluptatem','Panama','telechargement.jpg','rerum ea dolor'),
	 (10,375,98.0,'temporibus qui aut sit architecto aut molestiae hic eos asperiores et necessitatibus voluptatem neque hic molestias aut aliquid et in perferendis velit quae eos non voluptatum molestiae aut tenetur earum',1,1,'qui quasi necessitatibus ea quod fuga illo consectetur et consequatur',4814,'accusamus laudantium ratione','Suriname','telechargement.jpg','ut magni cumque'),
	 (10,460,37.0,'qui corrupti omnis eveniet qui alias qui ea soluta qui repellat perferendis ducimus aut et quis enim voluptas harum autem cumque quam veritatis aut laborum quia porro vel numquam in',5,1,'perferendis quam sunt doloribus rem nesciunt non aliquid quo neque',1499,'aspernatur ea minus','Laos','telechargement.jpg','error veritatis incidunt'),
	 (10,241,56.0,'occaecati quibusdam iste et facere est id doloribus reiciendis vero asperiores veritatis dolorum nemo unde quaerat dolorum neque laudantium assumenda illum ab distinctio fugit dolorum ea ipsam non quaerat consectetur',1,1,'dignissimos consectetur minus quis enim officiis qui beatae quis a',2254,'nisi soluta nam','Mauritanie','telechargement.jpg','aut dolor ullam'),
	 (10,419,52.0,'explicabo repudiandae omnis fuga nobis ex deserunt culpa et neque id et architecto enim dolores ratione qui placeat qui voluptates ipsa ut suscipit earum sed ea libero eligendi et explicabo',4,1,'iusto minus non alias debitis est non quas voluptatem sit',4061,'assumenda maiores molestiae','Tunisie','telechargement.jpg','reiciendis et incidunt'),
	 (10,297,99.0,'totam quod magni sit molestiae voluptatum corrupti dolor quidem quibusdam officia nesciunt quia unde voluptatem accusantium natus esse sit ut alias nulla est ea illum inventore libero est qui velit',4,1,'dolorem quos in dignissimos eligendi eius ut nisi at cum',3353,'quia culpa animi','Maroc','telechargement.jpg','voluptatibus ad facilis'),
	 (10,449,87.0,'et ipsum enim quia in voluptatum sunt est voluptatem soluta rem ipsum sit ea velit dignissimos aut veritatis omnis et est mollitia modi nobis commodi quia corrupti voluptatibus quia eligendi',1,1,'ea magnam debitis voluptatum expedita at optio occaecati voluptatem et',4599,'et impedit veritatis','Micronésie (États fédérés de)','telechargement.jpg','eius molestiae debitis'),
	 (10,380,59.0,'voluptate velit facilis qui hic quo aut quae debitis odit assumenda ab consequatur corrupti non ut qui mollitia ipsa sunt facere sit facilis ratione at quo nobis vero et eos',2,1,'tenetur et eius sit repellat corrupti est aliquam sapiente laborum',9818,'perspiciatis quod quo','Finlande','telechargement.jpg','tempore voluptatibus quia'),
	 (10,430,48.0,'quod consectetur in mollitia minus amet alias expedita iure nisi commodi tenetur occaecati dolore culpa eaque nostrum placeat ducimus quis in amet nostrum ut aut repudiandae accusantium facere magnam expedita',2,1,'ut molestiae unde consequatur sint sint doloribus aut omnis et',9509,'dolore optio pariatur','Vietnam','telechargement.jpg','et aliquid velit'),
	 (10,233,93.0,'dolores et eum soluta cupiditate eos quis sit aut molestiae cum et minima quisquam consequatur eos molestias quia et ea voluptas ut odit repellat delectus facilis aut sunt adipisci recusandae',1,1,'voluptatem quia doloribus rerum fugit a repellat consequuntur similique maxime',3214,'molestiae illo ratione','Martinique','telechargement.jpg','est ullam omnis');
INSERT INTO airbnbdata.logement (user_id_id,prix,taille,description,couchage,is_active,adresse,code_postal,ville,pays,image_path,name) VALUES
	 (10,247,66.0,'architecto quia quis eius sint quod voluptas velit expedita ex et ut pariatur possimus quibusdam temporibus fugit aliquam ipsum animi adipisci et expedita voluptatem aut in sint dolorem saepe tempora',5,1,'quos neque consequatur laborum voluptas et modi est sit quisquam',8382,'quia recusandae iure','Samoa','telechargement.jpg','illum et impedit'),
	 (10,274,75.0,'eius voluptatem rerum quo nostrum ut nam illo eum aut quasi pariatur non velit commodi doloribus ducimus praesentium ut aut enim esse illum eos voluptas eum blanditiis consequatur qui exercitationem',2,1,'dolores et minima aliquid dolores aut voluptatibus sed veritatis voluptate',7819,'minus repellat itaque','Wallis et Futuna (Îles)','telechargement.jpg','nam eaque vel'),
	 (10,273,64.0,'voluptatem officiis amet assumenda aliquam nostrum iusto est et tempore qui at sint laboriosam deserunt quos illo ut vel est culpa aut fugiat qui aperiam doloremque eos et vitae esse',5,1,'laboriosam deserunt omnis labore dolor debitis reprehenderit molestiae molestias dolorem',7553,'minus ullam nam','Guatemala','telechargement.jpg','aut qui rem'),
	 (10,180,99.0,'eius sapiente quo aliquam aliquid vitae placeat vitae cum beatae sit et praesentium explicabo fuga consequatur ipsum ipsa minima assumenda asperiores et sed ducimus omnis laudantium nihil distinctio voluptatem voluptatem',4,1,'voluptatem unde asperiores explicabo optio suscipit non qui rem dolorem',5156,'consequatur molestiae cupiditate','Grenade','telechargement.jpg','est qui quos'),
	 (10,469,80.0,'ducimus deserunt itaque odit quae aut minus aliquid dolorum ea doloremque laboriosam provident dolores quasi voluptas eos inventore aliquam ex et quia reiciendis repudiandae qui non tempora id consequatur rerum',3,1,'rerum delectus ut illo nostrum quibusdam dolor debitis culpa enim',1199,'neque impedit praesentium','Guinée','telechargement.jpg','occaecati accusantium cum'),
	 (10,413,56.0,'iusto tempore beatae et dolore asperiores unde fugiat nihil est natus ut vero est dolorum non facere iure a est ut asperiores dolor veritatis at totam sed voluptatibus voluptatum voluptates',3,1,'eius est possimus consectetur porro non impedit ullam odit officia',9426,'facilis natus iste','Moldavie','telechargement.jpg','voluptas voluptatum totam'),
	 (10,369,41.0,'ullam minus rerum provident aut voluptatum et temporibus nostrum quia maxime molestiae blanditiis aliquam quam atque et et et et quo natus quisquam unde ut ea omnis ullam et ipsam',5,1,'odit et illo velit culpa sit pariatur non ipsam illo',5428,'qui veniam ratione','Polynésie française','telechargement.jpg','earum laboriosam nemo'),
	 (10,447,46.0,'saepe sunt in qui occaecati praesentium ex cum animi voluptatum earum sed doloribus aspernatur tempore quia esse impedit animi beatae sit quia quia quo nam sapiente repudiandae quia atque voluptatem',1,1,'voluptates eum doloribus voluptatem ea laudantium voluptatibus assumenda modi voluptatem',3730,'quo fugiat aut','Guyane','telechargement.jpg','quae cum illum'),
	 (10,228,50.0,'nemo consequatur ullam voluptatem assumenda enim sed soluta officia aliquid incidunt illum dolore aliquam assumenda atque nulla quo iusto cumque error sit tempore qui minima ipsa alias molestiae voluptates enim',2,1,'dignissimos quo ut est rerum ut accusantium ad qui accusamus',1722,'nihil perspiciatis et','Djibouti','telechargement.jpg','sint consequuntur dolor'),
	 (10,231,62.0,'veniam aliquid ut neque repudiandae earum explicabo id doloremque id ut cumque rerum illum nostrum ut sapiente dolorem distinctio aliquid eligendi totam animi quas voluptatem beatae rem dolores ut doloribus',5,1,'illum fuga dolor dicta excepturi harum et quisquam velit dicta',6453,'ea laudantium ad','Afghanistan','telechargement.jpg','qui nisi perferendis');
INSERT INTO airbnbdata.logement (user_id_id,prix,taille,description,couchage,is_active,adresse,code_postal,ville,pays,image_path,name) VALUES
	 (10,169,92.0,'voluptatem beatae eligendi voluptatem omnis asperiores porro ut ipsum ea excepturi qui quos voluptas ea sunt illum molestias voluptatem aut consequatur ipsa atque occaecati sed iste id ipsum consequatur veritatis',1,1,'itaque voluptas quas aut fuga id laborum modi praesentium quia',9971,'quis omnis quo','Iran','telechargement.jpg','sapiente architecto perspiciatis'),
	 (10,400,54.0,'rerum debitis libero voluptatem aperiam incidunt ea quod reprehenderit amet possimus eos earum et officiis error nam in et dicta ad quam atque harum molestiae enim in ut occaecati maiores',4,1,'possimus quasi inventore ratione recusandae error voluptatem tempore repudiandae similique',9947,'omnis voluptate fugit','Australie','telechargement.jpg','maiores atque perferendis'),
	 (10,379,97.0,'perspiciatis enim maiores enim aut non et et nam ad labore quis praesentium esse doloribus qui eveniet recusandae qui aut quia sunt aliquid ducimus alias fuga aut facere consequuntur voluptatem',1,1,'dolorem porro ipsam aut voluptatibus et quia nihil error saepe',7946,'facere vero distinctio','Burkina Faso','telechargement.jpg','rerum a aliquam'),
	 (10,118,31.0,'nam cum ipsum aliquam saepe consectetur necessitatibus et voluptatem accusamus ullam occaecati doloribus officiis quia est qui in alias eaque dicta quaerat placeat quisquam placeat corrupti rerum minima rerum dolorem',3,1,'quia quam et reiciendis eveniet consequatur perspiciatis repellat voluptatibus pariatur',6533,'corporis nisi dolorem','Îles Mineures Éloignées des États-Unis','telechargement.jpg','saepe mollitia autem'),
	 (10,348,99.0,'omnis doloremque vel omnis nesciunt quos culpa repellendus possimus odit eveniet et non qui maxime nemo minus illum aliquid quia dolore sunt est temporibus nisi quis est eum eum labore',4,1,'qui ex fuga numquam consequatur unde quis illo qui sit',4827,'velit unde saepe','Nouvelle Calédonie','telechargement.jpg','architecto quis quia'),
	 (10,390,44.0,'eos hic dolorem aliquid magni dolore consectetur est consequatur ea est odit omnis rerum sed veniam autem et est sed consequatur quia consequuntur iure ut laboriosam explicabo commodi voluptatem est',1,1,'ab minus sunt quia doloribus aut exercitationem maxime doloremque natus',5012,'et ipsum nobis','Arménie','telechargement.jpg','voluptatem et dicta'),
	 (10,147,77.0,'non aut nisi sed nam et nesciunt eum ullam magni corrupti officia quidem aspernatur animi iure animi est neque inventore tempora nemo alias eos aut sit voluptatibus non sunt molestias',3,1,'fuga aspernatur sint explicabo ipsum vel eaque voluptatem fuga ullam',6531,'incidunt ullam est','Guyane','telechargement.jpg','dolorem deleniti et'),
	 (10,399,88.0,'assumenda vel qui rerum odit ipsa rerum consectetur est nemo dolor voluptatem rem distinctio quasi quae rerum perferendis necessitatibus eum vel omnis quam commodi atque nostrum autem rerum temporibus qui',5,1,'porro nisi animi asperiores accusamus iusto perferendis sapiente quis ratione',4218,'perspiciatis sed nostrum','Yougoslavie','telechargement.jpg','esse facere et'),
	 (10,146,41.0,'ratione est non occaecati repellat vitae laborum iste sed quo nesciunt odio aliquam maxime voluptatum maxime id sed culpa et saepe deleniti ut corporis qui dicta ipsa esse et voluptatem',4,1,'voluptas ipsa qui delectus in magnam eum voluptas odio voluptate',6973,'delectus placeat repellendus','Mayotte','telechargement.jpg','error ipsa ut'),
	 (10,271,74.0,'blanditiis quis repellendus quidem unde quo sint assumenda voluptas et laudantium et eligendi aut officiis nam magnam aut dignissimos odio libero quia quos magnam assumenda modi sed aut et rerum',3,1,'voluptate ut porro eius error fugit fuga saepe aliquid quis',1836,'placeat aut error','Tanzanie','telechargement.jpg','quos sit occaecati');
INSERT INTO airbnbdata.logement (user_id_id,prix,taille,description,couchage,is_active,adresse,code_postal,ville,pays,image_path,name) VALUES
	 (10,310,83.0,'facilis corporis non sed a id eos dolor tenetur expedita sit voluptates corrupti inventore est esse ut neque occaecati voluptas enim reprehenderit suscipit rerum nam alias nihil et totam cum',3,1,'sed quasi consequuntur sed placeat reprehenderit quo aliquid et ipsa',5295,'quia porro quam','Guyane','telechargement.jpg','at dolorem rerum'),
	 (10,346,100.0,'odit molestias quaerat ut ad dolor repudiandae neque aut sequi unde expedita alias voluptatem neque fugit accusantium corporis quae enim libero porro quasi est velit sed sunt labore dolorum voluptatem',1,1,'ea dolorum consequatur doloribus culpa laudantium animi omnis tempora aspernatur',7014,'corporis doloribus exercitationem','Samoa','telechargement.jpg','voluptatem consequatur eligendi'),
	 (10,454,38.0,'eos beatae fugit veniam dolorem similique eaque et voluptatem dignissimos inventore ad expedita fuga ut accusantium qui soluta corrupti delectus dolores est blanditiis sit veritatis nulla eum reprehenderit aut doloremque',4,1,'cum magnam facere cupiditate pariatur at laudantium qui culpa id',3672,'dolore sed iste','Guinée','telechargement.jpg','qui voluptatibus deserunt'),
	 (10,346,86.0,'facilis doloribus temporibus et veniam nulla repellendus delectus quas deleniti reiciendis aut et corporis placeat soluta fugit vitae qui molestiae voluptate ea earum et aliquid nulla voluptatem quam id ea',5,1,'rerum id aspernatur autem at architecto optio nobis repudiandae aut',8315,'dolorem consequatur molestias','Pologne','telechargement.jpg','hic esse natus'),
	 (10,148,60.0,'sequi esse ad voluptatem voluptatem atque aut accusamus eum qui facere incidunt iusto est porro consectetur facilis dolores a consequatur illum sapiente necessitatibus voluptatibus qui voluptatem odit rerum molestiae iste',2,1,'at ut quod magnam aliquam ratione voluptatem harum aliquam culpa',7026,'optio quis sequi','Territoires français du sud','telechargement.jpg','est assumenda praesentium'),
	 (10,314,63.0,'mollitia dignissimos asperiores dolorum occaecati nemo odio repellendus incidunt error ea enim libero itaque provident sit in non quia est velit laboriosam quia molestias et cupiditate cum qui quia voluptates',2,1,'aut quisquam doloremque esse dolor aut aperiam voluptas id tempore',7495,'ut repellendus quisquam','Dominique','telechargement.jpg','quibusdam praesentium eos'),
	 (10,214,36.0,'eveniet quo corporis nostrum sit sunt nihil quidem veritatis illum consequatur quia earum quia porro sequi labore quibusdam eos praesentium ea et libero ad temporibus eius nemo facilis qui modi',1,1,'ratione sint repellat ipsam ab cumque consequatur placeat non aperiam',5801,'nulla commodi aut','Hongrie','telechargement.jpg','libero est voluptate'),
	 (10,237,63.0,'odio autem aspernatur ratione architecto nihil consequatur quod consequatur molestias voluptatum qui aspernatur repellendus ut sequi et debitis qui temporibus ad sequi velit dolor beatae ipsum animi totam cum atque',4,1,'et doloremque non quaerat dolores molestias dolores qui maiores odio',7195,'et sed voluptas','Djibouti','telechargement.jpg','nam aut error'),
	 (10,371,90.0,'est cumque distinctio qui magni aut magni nihil rerum officia reprehenderit eos voluptatum quia magnam maiores voluptatem ab aut nostrum laboriosam numquam inventore dolor molestiae nobis sint aperiam a est',1,1,'tempore blanditiis et dolores reprehenderit assumenda saepe sit aperiam suscipit',2494,'nesciunt blanditiis mollitia','El Salvador','telechargement.jpg','voluptatem velit sunt'),
	 (10,187,98.0,'doloremque amet architecto ipsa et eius velit delectus nesciunt qui in repellendus numquam expedita dolorem rerum eum officiis autem consectetur ex pariatur voluptatem ut quis atque ipsum rerum et omnis',4,1,'ratione accusamus suscipit molestiae laboriosam rerum quasi eum perspiciatis consequuntur',6684,'et consequatur illo','Costa Rica','telechargement.jpg','quod dolores voluptas');
INSERT INTO airbnbdata.logement (user_id_id,prix,taille,description,couchage,is_active,adresse,code_postal,ville,pays,image_path,name) VALUES
	 (10,225,38.0,'sed mollitia explicabo et totam adipisci voluptatem mollitia itaque error nam ullam et quam aut error in provident praesentium voluptate eos repudiandae sit magni doloribus et necessitatibus sequi consequatur est',1,1,'et nam et non incidunt dolores alias corrupti neque et',2304,'id et rerum','Irlande','telechargement.jpg','voluptatem ut aliquam'),
	 (10,473,60.0,'iste provident suscipit est in non doloribus sapiente tenetur ex et deleniti omnis veritatis esse dolores eaque deserunt ut deserunt quidem officia sed voluptas et ullam quo voluptatibus reiciendis laboriosam',3,1,'voluptatum ut voluptas nemo error quaerat eius ut aliquam doloribus',9023,'laudantium dolorum voluptatem','Martinique','telechargement.jpg','consequuntur in est'),
	 (10,405,75.0,'pariatur dolorum velit esse consequatur eos et dolores ad reiciendis voluptas sunt animi fuga quaerat sit exercitationem est vel libero sint et non nesciunt vel perferendis odit ut omnis iusto',4,1,'in voluptatum cum quas aspernatur consequuntur quibusdam animi similique quia',7103,'vero molestias eveniet','Hong Kong','telechargement.jpg','vel quia ut'),
	 (10,126,41.0,'voluptatem a culpa dolores fugiat cumque aspernatur id vero placeat deserunt laboriosam minus quam vel incidunt est repellat assumenda excepturi error dolore aut deserunt ut nesciunt delectus velit accusamus dolorem',2,1,'impedit molestiae consequuntur totam numquam dolore dolores consequatur maxime sit',5698,'nihil quibusdam aspernatur','Roumanie','telechargement.jpg','sunt eum ipsa'),
	 (10,288,73.0,'quo sit dolorem nemo debitis animi eaque nisi vel vero ut eum occaecati magnam est vitae facilis molestiae consequatur reiciendis quam porro soluta eum veniam voluptas blanditiis quos ut consequatur',4,1,'rerum id quod tempora ut molestiae est quos dolore atque',3294,'non est sit','Brésil','telechargement.jpg','velit adipisci perferendis'),
	 (10,443,95.0,'omnis ipsum similique quasi voluptatem harum quam sunt saepe aspernatur dolor omnis dolor doloremque est quis illo architecto facere est eius vel numquam et itaque enim non ipsum tenetur nostrum',1,1,'non eos ea deserunt velit minima rerum consectetur omnis enim',3218,'atque quae distinctio','Cameroun','telechargement.jpg','ut qui earum'),
	 (10,327,58.0,'dignissimos soluta nihil assumenda possimus commodi debitis vero cumque eius odit eaque veniam tempora incidunt aut deleniti aut repellendus ipsa harum perferendis quia autem assumenda qui sunt soluta saepe dolor',2,1,'et sit nisi fugit ut est quae mollitia aperiam sed',1597,'sed ullam rerum','Colombie','telechargement.jpg','fuga rerum iure'),
	 (10,241,63.0,'in qui nulla vitae impedit unde dicta odio quaerat sunt aut et omnis minus sit voluptas quo possimus laborum ut repudiandae quibusdam quo et rerum sapiente ut ex a voluptatum',3,1,'saepe et sunt molestiae impedit est optio qui numquam suscipit',7085,'quod similique at','Andorre','telechargement.jpg','facere laboriosam consequatur'),
	 (10,368,93.0,'atque quam iure debitis nesciunt inventore consequuntur voluptates praesentium veniam aspernatur facere quam consequatur aut et vero voluptatem adipisci magni sint autem unde similique eos ratione illum qui iusto blanditiis',5,1,'totam quae aut illum dolorum vel voluptatem velit veritatis autem',2542,'est corporis dolorem','Vanuatu','telechargement.jpg','rem optio autem'),
	 (10,435,86.0,'laborum nemo repudiandae aut dolorem quod et ullam molestiae ullam voluptas autem qui et maiores voluptates adipisci ipsa natus in ex hic quidem et blanditiis ut est rerum consequuntur eius',5,1,'tempore voluptas sint dolorum consequatur ullam suscipit sed repudiandae id',7029,'est veniam voluptatem','Grèce','telechargement.jpg','voluptate rerum est');
INSERT INTO airbnbdata.logement (user_id_id,prix,taille,description,couchage,is_active,adresse,code_postal,ville,pays,image_path,name) VALUES
	 (10,306,70.0,'accusamus est non quia cumque commodi animi facilis quia eaque dolor veniam molestias autem ratione dolorem laboriosam et pariatur et quis ut voluptas officia dignissimos pariatur fugiat voluptatem aut illo',3,1,'dolorum consequuntur aut maiores nemo quod deleniti dolorem ea itaque',2938,'asperiores natus nemo','Bangladesh','telechargement.jpg','aliquid hic et'),
	 (10,481,35.0,'aliquid assumenda ab accusamus repudiandae distinctio aut animi quam doloribus suscipit voluptatem sequi harum aliquid magnam minima dicta libero excepturi suscipit numquam sed dolor blanditiis eveniet doloremque ut saepe quia',4,1,'impedit eum nostrum doloribus quia voluptatibus fuga minima numquam quae',4916,'qui sit dolore','Canada','telechargement.jpg','laborum fuga expedita'),
	 (10,471,36.0,'ea facilis sint voluptas voluptas in velit ea voluptates sit odit et accusantium qui vitae dolores quos earum consectetur earum odit fugit dolor modi fuga ut eveniet temporibus ea est',1,1,'nemo aperiam quam consectetur et nostrum doloremque qui atque error',4489,'omnis beatae sit','Libye','telechargement.jpg','velit autem placeat'),
	 (10,315,33.0,'sed autem nostrum vero voluptatibus reiciendis aut consectetur ea autem et aliquid vel molestias dolorum numquam quis ex nihil sapiente quia est quia non quod mollitia ut voluptas atque dolor',1,1,'facere consequatur soluta delectus qui error nesciunt et quia qui',7737,'quam corrupti et','République Dominicaine','telechargement.jpg','iste nulla cumque'),
	 (10,261,64.0,'dignissimos saepe laboriosam iusto deserunt assumenda consequatur at recusandae eveniet quasi similique et occaecati consectetur deleniti tempore rem ut voluptas quisquam est placeat quasi asperiores aut aut harum pariatur magnam',2,1,'voluptatem quia ut magni officia et dolorum officia est neque',1170,'qui voluptate modi','Macau','telechargement.jpg','quo est dolorem'),
	 (10,158,34.0,'ea pariatur id reiciendis doloremque ad eaque eos molestiae occaecati laudantium laboriosam quae quibusdam nemo est doloremque qui et eos tenetur et consequuntur ipsa est laudantium magnam aspernatur voluptatibus dolorum',3,1,'consectetur delectus qui ut voluptatem aperiam rerum facere quasi rerum',9888,'hic facere dicta','Svalbard et Jan Mayen (Îles)','telechargement.jpg','numquam vel eius'),
	 (10,302,80.0,'in sint ex cum assumenda et distinctio sint consequuntur sint accusantium rerum laboriosam vitae debitis quis debitis dolores soluta ipsum voluptas excepturi voluptatem incidunt accusamus vel aut sint ad est',1,1,'nulla officiis magnam architecto laudantium consequatur ut ipsam architecto non',2851,'excepturi perspiciatis molestiae','Cayman (Îles)','telechargement.jpg','molestiae ea sit'),
	 (10,449,55.0,'quam sit expedita sed qui vero accusantium deserunt voluptatum et dolorem neque eos nihil inventore distinctio voluptas laboriosam vel dicta eos ad numquam enim vero et eos ut ipsa deleniti',1,1,'et vel tempora voluptatem odio non sequi aperiam eos qui',2994,'consequatur iure consequatur','Antarctique','telechargement.jpg','doloribus pariatur voluptatibus'),
	 (10,483,83.0,'error magni omnis aut eligendi debitis quia atque dolorem ullam eveniet aut architecto ex sed quis ipsam quos placeat et maiores corporis et inventore dolor itaque cupiditate consectetur ut nisi',5,1,'est maxime error natus cupiditate eum et fugiat ipsa magni',6334,'possimus quam omnis','Japon','telechargement.jpg','repellendus deserunt consequatur'),
	 (10,122,99.0,'ea a sunt modi non minus ducimus dolor sequi sint magnam eos doloribus perferendis nesciunt consequatur perferendis accusantium doloribus molestias qui saepe sed sit doloribus ut et molestiae temporibus ipsam',4,1,'qui ea libero sit molestias perferendis nobis aut suscipit voluptatem',5964,'labore et in','Malaisie','telechargement.jpg','veritatis sed ut');
INSERT INTO airbnbdata.logement (user_id_id,prix,taille,description,couchage,is_active,adresse,code_postal,ville,pays,image_path,name) VALUES
	 (10,271,60.0,'adipisci laudantium et eius veniam consequatur voluptatem et voluptas soluta nemo quis accusamus est voluptatum recusandae voluptatem eius qui dicta porro perferendis sit eos adipisci sit eligendi et iste animi',2,1,'ducimus quia vel quo doloribus vitae quis laudantium et velit',9987,'architecto eum sed','Bouvet (Îles)','telechargement.jpg','ipsum est culpa'),
	 (10,193,55.0,'labore excepturi consectetur mollitia accusamus cum laboriosam hic at ut consectetur nesciunt est ut necessitatibus aspernatur voluptates soluta totam qui aut et quis vitae consequatur repudiandae ut sequi inventore et',2,1,'quo voluptates officiis rem assumenda unde sint earum qui quasi',7308,'repudiandae sapiente vel','Samoa','telechargement.jpg','sunt cumque quia'),
	 (10,135,87.0,'dicta quisquam modi quis dolor asperiores explicabo deleniti nihil aspernatur qui aut doloribus labore quia est maiores iusto consequatur nostrum itaque natus quia aut minima qui sit dolorem est nesciunt',5,1,'consequatur modi quia ex totam et fugiat temporibus aperiam molestiae',6574,'ullam fuga officiis','Égypte','telechargement.jpg','perferendis illo quia'),
	 (10,170,60.0,'ex aspernatur qui qui illo iste rem aspernatur culpa asperiores numquam quis dolorem ut dolore tempora numquam est culpa ut suscipit sint minima non ipsam soluta maxime cum non delectus',3,1,'assumenda aspernatur harum veritatis eligendi voluptatem cum doloremque magnam illum',8517,'est consectetur quidem','Paraguay','telechargement.jpg','porro ut a'),
	 (10,264,75.0,'adipisci voluptatem hic dolorem voluptates magnam earum eius odio ducimus dolorem pariatur laborum dignissimos excepturi consequuntur aliquam quam animi consequatur laboriosam quia ipsum sint dignissimos molestiae magnam praesentium consequatur corrupti',2,1,'numquam molestiae a impedit est eos rerum aut ipsum quia',2512,'autem quia est','Tchad','telechargement.jpg','sunt corrupti non'),
	 (10,118,71.0,'quam dolore vitae omnis ipsa perspiciatis repellat amet ut sed quod ut occaecati quis ab sint impedit suscipit fuga explicabo aut aut temporibus esse tenetur veniam possimus omnis eos sit',1,1,'sed doloremque porro quibusdam adipisci et dignissimos ut ut molestias',8754,'necessitatibus ut numquam','Singapour','telechargement.jpg','perspiciatis sequi quo'),
	 (10,348,34.0,'suscipit ut libero rerum accusantium temporibus possimus velit recusandae eius dolore soluta ea in officia in iure quasi nisi voluptas accusantium iure quia distinctio aliquid molestiae nihil corrupti tenetur accusantium',3,1,'qui impedit eius illum pariatur et dolores enim rem voluptatum',8828,'ducimus sit voluptates','Laos','telechargement.jpg','illum quo laborum'),
	 (10,386,84.0,'mollitia at qui perferendis assumenda non quia asperiores voluptate enim rerum quaerat accusamus occaecati et ab ea nam consequatur beatae optio nihil unde ipsa aut nobis porro rerum et consequatur',4,1,'magni debitis qui dolores quidem ut iusto quia nemo vel',5048,'quisquam sed commodi','Guadeloupe','telechargement.jpg','est dolore occaecati'),
	 (10,413,95.0,'aut libero voluptatem quibusdam commodi eligendi saepe repudiandae voluptatem quia qui adipisci est quis suscipit suscipit aut perspiciatis rerum placeat soluta delectus similique corrupti voluptas dolores eveniet inventore voluptas harum',5,1,'cum mollitia necessitatibus et doloribus eligendi incidunt eius ullam voluptatum',6572,'dolor optio sint','Malawi','telechargement.jpg','qui voluptas similique'),
	 (10,411,79.0,'saepe enim rerum aut necessitatibus facere reiciendis iure quo unde voluptatem distinctio minus est provident perspiciatis est quibusdam laboriosam magni molestias animi asperiores quo suscipit quia voluptatem et atque dolor',2,1,'cumque nam voluptas sint maiores illum aut qui aut eum',1844,'dolores ullam ipsum','Tuvalu','telechargement.jpg','ipsam molestias rerum');
INSERT INTO airbnbdata.logement (user_id_id,prix,taille,description,couchage,is_active,adresse,code_postal,ville,pays,image_path,name) VALUES
	 (10,253,76.0,'quidem id et id atque quos non placeat rerum voluptas dolorem vitae quo autem consequatur ea quaerat deserunt qui tempore et modi ut veritatis animi odit voluptas consequuntur perspiciatis quia',2,1,'alias dolor molestiae omnis laudantium tenetur cupiditate expedita et veritatis',4825,'est ipsam sequi','Honduras','telechargement.jpg','aut sit voluptas'),
	 (10,160,71.0,'quidem voluptatem autem sunt eveniet sed sed animi est eveniet sint alias error atque tempore sed quis laudantium voluptas modi quibusdam blanditiis vel mollitia et molestiae nam mollitia unde aliquam',3,1,'voluptatibus est ea rem culpa rerum corporis sit quis sunt',6116,'debitis qui quibusdam','Angola','telechargement.jpg','voluptas voluptate quam'),
	 (10,245,85.0,'nostrum magni repudiandae numquam fuga maiores recusandae illo consectetur corrupti expedita quaerat dolores enim voluptas minima non qui quo tempore quia impedit est adipisci deserunt blanditiis modi perferendis error illum',5,1,'nam dolores quos consequuntur impedit ducimus exercitationem consequuntur perferendis libero',4232,'consequatur consequatur qui','Guinée','telechargement.jpg','nisi et sequi'),
	 (10,409,80.0,'laudantium occaecati sed sint ut debitis dolor dolores quos dolor adipisci id illum similique non tempora consequatur exercitationem in et accusantium iste quia totam doloribus eos aut voluptas est corrupti',3,1,'nihil id aspernatur quo ut rerum et culpa animi odit',9933,'ad asperiores impedit','Îles Mineures Éloignées des États-Unis','telechargement.jpg','illo nihil totam'),
	 (10,420,74.0,'et veritatis occaecati laudantium ad iure voluptatibus suscipit totam et accusantium quam voluptatem minima accusamus sit quia qui ullam ea autem voluptatum perferendis id et adipisci exercitationem sed cupiditate aut',1,1,'deleniti perspiciatis natus vero laborum itaque ea nihil voluptatem distinctio',6779,'officia expedita doloremque','Ouganda','telechargement.jpg','est dolorem error'),
	 (10,359,90.0,'dignissimos nisi ut cum sit illo eum error culpa voluptate voluptate nemo quod repudiandae molestias consectetur repellendus mollitia ut illo et ducimus fuga voluptatibus repudiandae dignissimos eos omnis velit esse',3,1,'optio cum rerum ratione ullam libero esse dolores animi deleniti',9952,'temporibus quo quis','Niger','telechargement.jpg','sed doloribus commodi'),
	 (10,467,86.0,'laboriosam deleniti ut perferendis repellat voluptas saepe facilis nisi ut atque quia non aut mollitia aliquid consequuntur harum repellat distinctio nihil saepe excepturi doloribus ab rerum molestiae officiis beatae explicabo',3,1,'quis id alias et corporis vitae dignissimos sit voluptatem aut',6985,'unde aut nihil','Sénégal','telechargement.jpg','accusantium omnis maiores'),
	 (10,435,90.0,'dolor perferendis rerum et harum dolorem sapiente ad eum et eum suscipit ad odio sunt et reiciendis dolorem dolor corporis porro laudantium perspiciatis est facere possimus molestiae nulla officia corporis',3,1,'beatae fuga nihil tenetur eligendi minima officia ut voluptas sed',2689,'perferendis et totam','Polynésie française','telechargement.jpg','laboriosam quos cum'),
	 (10,365,80.0,'sint libero hic rem suscipit est voluptas vel fugiat deserunt sed sapiente est vel qui animi unde corporis aut expedita ipsa earum sed ex voluptatum ex consectetur ut architecto dolorem',5,1,'aut architecto occaecati voluptas voluptatibus est consequuntur ut delectus beatae',6221,'exercitationem praesentium sequi','Brésil','telechargement.jpg','corporis fugiat excepturi'),
	 (10,450,65.0,'similique asperiores numquam corrupti vel debitis sapiente ex aut cum quis praesentium totam qui ex quos et quasi sit earum optio esse veritatis omnis optio quia rem non excepturi qui',4,1,'ipsa aliquam fugit corrupti cupiditate ut inventore debitis rerum provident',1939,'aut doloribus consequatur','Cambodge','telechargement.jpg','magni ipsa officia');
INSERT INTO airbnbdata.logement (user_id_id,prix,taille,description,couchage,is_active,adresse,code_postal,ville,pays,image_path,name) VALUES
	 (12,2,3.0,'ppp',1,1,'mimosa',3,'popo','Belgique','default-65bb9791b8083843516432.jpg','eee');
