vich_uploader:
    db_driver: orm

    mappings:
        images:
            uri_prefix: /img/imageLogement
            upload_destination: '%kernel.project_dir%/public/img/imageLogement'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
